// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace XunitDemo.Entity
{
    using System;
    using System.Data.Entity;

    // Category Sales for 1997
    public partial class CategorySalesFor1997
    {
        public string CategoryName { get; set; } // CategoryName
        public decimal? CategorySales { get; set; } // CategorySales
        
        public CategorySalesFor1997()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
